/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tic_tac_toe;

import java.awt.Color;

/**
 *
 * @author GoldenTech
 */
public class singleDB extends javax.swing.JFrame {

    /**
     * Creates new form singleDB
     */
    public singleDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main1 = new javax.swing.JPanel();
        header2 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        backP = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        btns1 = new javax.swing.JPanel();
        easy1 = new javax.swing.JPanel();
        easyBtn1 = new javax.swing.JLabel();
        medium1 = new javax.swing.JPanel();
        mediumBtn1 = new javax.swing.JLabel();
        hard1 = new javax.swing.JPanel();
        hardBtn1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main1.setBackground(new java.awt.Color(51, 51, 0));
        main1.setLayout(new java.awt.BorderLayout());

        header2.setBackground(new java.awt.Color(0, 0, 0));

        title1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        title1.setForeground(new java.awt.Color(0, 0, 255));
        title1.setText("         TIC TAC TOE");

        backP.setBackground(new java.awt.Color(0, 0, 0));

        back.setFont(new java.awt.Font("Harlow Solid Italic", 0, 48)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("<");
        back.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backPLayout = new javax.swing.GroupLayout(backP);
        backP.setLayout(backPLayout);
        backPLayout.setHorizontalGroup(
            backPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backPLayout.setVerticalGroup(
            backPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2Layout.createSequentialGroup()
                .addComponent(backP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(header2Layout.createSequentialGroup()
                .addComponent(backP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        main1.add(header2, java.awt.BorderLayout.PAGE_START);

        btns1.setBackground(new java.awt.Color(0, 0, 255));

        easy1.setBackground(new java.awt.Color(0, 0, 0));
        easy1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 2));

        easyBtn1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        easyBtn1.setForeground(new java.awt.Color(0, 0, 255));
        easyBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        easyBtn1.setText("Easy");
        easyBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        easyBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                easyBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                easyBtn1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout easy1Layout = new javax.swing.GroupLayout(easy1);
        easy1.setLayout(easy1Layout);
        easy1Layout.setHorizontalGroup(
            easy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(easyBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        easy1Layout.setVerticalGroup(
            easy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(easyBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        medium1.setBackground(new java.awt.Color(0, 0, 0));
        medium1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));

        mediumBtn1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        mediumBtn1.setForeground(new java.awt.Color(0, 0, 255));
        mediumBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mediumBtn1.setText("Medium");
        mediumBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mediumBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediumBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mediumBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mediumBtn1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout medium1Layout = new javax.swing.GroupLayout(medium1);
        medium1.setLayout(medium1Layout);
        medium1Layout.setHorizontalGroup(
            medium1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mediumBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        medium1Layout.setVerticalGroup(
            medium1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mediumBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        hard1.setBackground(new java.awt.Color(0, 0, 0));
        hard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));

        hardBtn1.setBackground(new java.awt.Color(255, 0, 0));
        hardBtn1.setFont(new java.awt.Font("Ravie", 0, 14)); // NOI18N
        hardBtn1.setForeground(new java.awt.Color(0, 0, 255));
        hardBtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hardBtn1.setText("Hard");
        hardBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hardBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hardBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hardBtn1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout hard1Layout = new javax.swing.GroupLayout(hard1);
        hard1.setLayout(hard1Layout);
        hard1Layout.setHorizontalGroup(
            hard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hardBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        hard1Layout.setVerticalGroup(
            hard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hardBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btns1Layout = new javax.swing.GroupLayout(btns1);
        btns1.setLayout(btns1Layout);
        btns1Layout.setHorizontalGroup(
            btns1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btns1Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(btns1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(easy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medium1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        btns1Layout.setVerticalGroup(
            btns1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btns1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(easy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(medium1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(hard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        main1.add(btns1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        main f = new main();
        this.setVisible(false);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        backP.setBackground(Color.gray);
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
       backP.setBackground(Color.black);
    }//GEN-LAST:event_backMouseExited

    private void easyBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyBtn1MouseEntered
        easy1.setBackground(Color.gray);
    }//GEN-LAST:event_easyBtn1MouseEntered

    private void easyBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyBtn1MouseExited
         easy1.setBackground(Color.black);
    }//GEN-LAST:event_easyBtn1MouseExited

    private void mediumBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumBtn1MouseEntered
         medium1.setBackground(Color.gray);
    }//GEN-LAST:event_mediumBtn1MouseEntered

    private void mediumBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumBtn1MouseExited
         medium1.setBackground(Color.black);
    }//GEN-LAST:event_mediumBtn1MouseExited

    private void hardBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardBtn1MouseEntered
         hard1.setBackground(Color.gray);
    }//GEN-LAST:event_hardBtn1MouseEntered

    private void hardBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardBtn1MouseExited
       hard1.setBackground(Color.black);
    }//GEN-LAST:event_hardBtn1MouseExited

    private void easyBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyBtn1MouseClicked
        easy f = new easy();
        this.setVisible(false);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_easyBtn1MouseClicked

    private void mediumBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumBtn1MouseClicked
        mediumMode f = new mediumMode();
        this.setVisible(false);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_mediumBtn1MouseClicked

    private void hardBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardBtn1MouseClicked
        hardMode f = new hardMode();
        this.setVisible(false);
        f.setVisible(true);
        f.setLocationRelativeTo(null);
    }//GEN-LAST:event_hardBtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(singleDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(singleDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(singleDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(singleDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               singleDB s = new singleDB();
               s.setVisible(true);
               s.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel backP;
    private javax.swing.JPanel btns1;
    private javax.swing.JPanel easy1;
    private javax.swing.JLabel easyBtn1;
    private javax.swing.JPanel hard1;
    private javax.swing.JLabel hardBtn1;
    private javax.swing.JPanel header2;
    private javax.swing.JPanel main1;
    private javax.swing.JPanel medium1;
    private javax.swing.JLabel mediumBtn1;
    private javax.swing.JLabel title1;
    // End of variables declaration//GEN-END:variables
}
